config/routes.rb
Rails.application.routes.draw do
 

  resources :main_ads

  resources :advert3s

  resources :advert2s

  resources :advert1s

  devise_for :users
  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
  end

  resources :events
  resources :homes
  
  root 'homes#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
	has_attached_file :image, :styles => { :large => "682x90", :medium => "237x400", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/advert1.rb
class Advert1 < ActiveRecord::Base
	has_attached_file :image, :styles => { :large => "680x90>", :medium => "230x400>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/advert2.rb
class Advert2 < ActiveRecord::Base
	has_attached_file :image, :styles => { :large => "680x90>", :medium => "230x400>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/advert3.rb
class Advert3 < ActiveRecord::Base
	has_attached_file :image, :styles => { :large => "680x90>", :medium => "230x400>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/advertise.rb
class Advertise < ActiveRecord::Base

    has_attached_file :image, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "150x150>" }

    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/event.rb
#require 'elasticsearch/model'

class Event < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :category, :location, :country, :venue, :name, :theme, presence: true

  belongs_to :user
  
  #relationship for industry name and event
  belongs_to :industry

  #adding elsatic search models
    #include Elasticsearch::Model
    #include Elasticsearch::Model::Callbacks

  #searchable do
    #text :category, :location, :country, :venue, :name, :theme
  #end

  #custom search
  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['category LIKE ? OR venue LIKE ?', search_condition, search_condition])
  end

  #def self.search
    #where("email like ?", "%#{query}")
  #end


  def Event.find_categories(string)
  	return found_event = Event.find_by_category(string)
  end

  def Event.find_countries(string)
    return found_event = Event.find_by_country(string)
  end


end
#Event.import # for auto sync model with elastic search
#case insensitivity


# rails g migration add_industry_to_event industry:references

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/industry.rb
class Industry < ActiveRecord::Base
	has_many :events, :dependent => :nullify
end

app/models/main_ad.rb
class MainAd < ActiveRecord::Base
	has_attached_file :image, :styles => { :large => "680x90#", :medium => "230x400#", :thumb => "150x150>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events	
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:image)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @homes = Home.all
  end
end

app/controllers/main_ads_controller.rb
class MainAdsController < ApplicationController
  before_action :set_main_ad, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /main_ads
  # GET /main_ads.json
  def index
    @main_ads = MainAd.all

    @advert1s = Advert1.order('created_at DESC').limit(1) 
    @advert2s = Advert2.order('created_at DESC').limit(1) 
    @advert3s = Advert3.order('created_at DESC').limit(1)
  end

  # GET /main_ads/1
  # GET /main_ads/1.json
  def show
  end

  # GET /main_ads/new
  def new
    @main_ad = MainAd.new
  end

  # GET /main_ads/1/edit
  def edit
  end

  # POST /main_ads
  # POST /main_ads.json
  def create
    @main_ad = MainAd.new(main_ad_params)

    respond_to do |format|
      if @main_ad.save
        format.html { redirect_to @main_ad, notice: 'Main ad was successfully created.' }
        format.json { render :show, status: :created, location: @main_ad }
      else
        format.html { render :new }
        format.json { render json: @main_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_ads/1
  # PATCH/PUT /main_ads/1.json
  def update
    respond_to do |format|
      if @main_ad.update(main_ad_params)
        format.html { redirect_to @main_ad, notice: 'Main ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_ad }
      else
        format.html { render :edit }
        format.json { render json: @main_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_ads/1
  # DELETE /main_ads/1.json
  def destroy
    @main_ad.destroy
    respond_to do |format|
      format.html { redirect_to main_ads_url, notice: 'Main ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_ad
      @main_ad = MainAd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_ad_params
      params.require(:main_ad).permit(:image, :link)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/advert1s_helper.rb
module Advert1sHelper
end

app/helpers/advert2s_helper.rb
module Advert2sHelper
end

app/helpers/advert3s_helper.rb
module Advert3sHelper
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/main_ads_helper.rb
module MainAdsHelper
end

app/views/main_ads/_form.html.erb
<%= form_for @main_ad, :html => { :multipart => true } do |f| %>
  <% if @main_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main_ad.errors.count, "error") %> prohibited this main_ad from being saved:</h2>

      <ul>
      <% @main_ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/main_ads/edit.html.erb
<h1>Editing Main Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @main_ad %> |
<%= link_to 'Back', main_ads_path %>

app/views/main_ads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Main Ads</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @main_ads.each do |main_ad| %>
      <tr>
        <td><%= image_tag main_ad.image.url(:medium) %></td>
      </tr>
    <% end %>
    
    <% @advert1s.each do |advert1| %>
      <tr>
        <td><%= image_tag advert1.image.url(:medium) %></td>
      </tr>
    <% end %>

    <% @advert2s.each do |advert2| %>
      <tr>
        <td><%= image_tag advert2.image.url(:medium) %></td>
      </tr>
    <% end %>

    <% @advert3s.each do |advert3| %>
      <tr>
        <td><%= image_tag advert3.image.url(:medium) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Main ad', new_main_ad_path %>

app/views/main_ads/new.html.erb
<h1>New Main Ad</h1>

<%= render 'form' %>

<%= link_to 'Back', main_ads_path %>

app/views/main_ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= link_to (image_tag @main_ad.image.url(:medium)), @main_ad.link, target: "_blank" %>
</p>

<!--<p>
  <strong>Link:</strong>
  <%= @main_ad.link %>
</p>-->

<%= link_to 'Edit', edit_main_ad_path(@main_ad) %> |
<%= link_to 'Back', main_ads_path %>