config/routes.rb
Rails.application.routes.draw do
 

  resources :main_ads

  resources :advert3s

  resources :advert2s

  resources :advert1s

  devise_for :users
  as :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
  end

  resources :events
  resources :homes
  
  root 'homes#index'
end

app/models/event.rb
#require 'elasticsearch/model'

class Event < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :category, :location, :country, :venue, :name, :theme, presence: true

  belongs_to :user
  
  #relationship for industry name and event
  belongs_to :industry

  #adding elsatic search models
    #include Elasticsearch::Model
    #include Elasticsearch::Model::Callbacks

  #searchable do
    #text :category, :location, :country, :venue, :name, :theme
  #end

  #custom search
  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['category LIKE ? OR venue LIKE ?', search_condition, search_condition])
  end

  #def self.search
    #where("email like ?", "%#{query}")
  #end


  def Event.find_categories(string)
  	return found_event = Event.find_by_category(string)
  end

  def Event.find_countries(string)
    return found_event = Event.find_by_country(string)
  end


end
#Event.import # for auto sync model with elastic search
#case insensitivity


# rails g migration add_industry_to_event industry:references

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /events
  # GET /events.json

  def index
    @main_ads = MainAd.all

    @advert1s = Advert1.order('created_at DESC').limit(1) 
    @advert2s = Advert2.order('created_at DESC').limit(1) 
    @advert3s = Advert3.order('created_at DESC').limit(1) 
    
    if params.has_key?("industry")
      @events = Event.where(category: params[:industry]).order("created_at DESC").paginate(page: params[:page], per_page: 10)
    elsif params.has_key?("country")
            @events = Event.where(country: params[:country]).order("created_at DESC").paginate(page: params[:page], per_page: 10)
      elsif params[:search]
        #custom search. no going back to model
        @events = Event.where("category LIKE ? OR venue LIKE ? OR name LIKE ? OR theme LIKE? OR company LIKE? OR country LIKE? OR location LIKE?",params[:search], params[:search], params[:search], params[:search], params[:search], params[:search], params[:search]).paginate(page: params[:page], per_page: 10)
          # @events = Event.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 10)
      else
        @events = Event.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)

      #search with sunspot
      #@query = Event.search do
          #fulltext params[:search]
      #end
      #@events = Event.where(id: @query.results.map(&:id)).order("created_at DESC").paginate(page: params[:page], per_page: 10)
    end

=begin    
    code to hide past dates. to be refined later
    @events = Event.find(:all, 
    :order => "date", 
    :conditions => ['date >= ?', Date.today]
    ).paginate(:per_page => 10, :page => params[:page])
=end
  end


  # GET /events/1
  # GET /events/1.json
  def show
  end

  def find_category (string)
    @event = Event.find_categories(string)
  end
  helper_method :find_category

  def find_country (string)
    @event = Event.find_countries(string)
  end
  helper_method :find_country

  def search
    @events = Event.search params[:search]
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

 


  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully Deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:image, :name, :organizer, :category, :date, :location, :link, :theme, :venue, :company, :country, :tag_list => [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<!-- styles and scripts -->
<style type="text/css">
.submit > a{
  background: #2471FF;
  border: none;
  padding: 10px 20px 10px 20px;
  border-bottom: 3px solid #5994FF;
  border-radius: 3px;
  color: #D2E2FF;
}
.form-style-7{
    max-width:400px;
    margin:50px auto;
    background:#fff;
    border-radius:2px;
    padding:20px;
    font-family: Corbel;
}
.form-style-7 h1{
    display: block;
    text-align: center;
    padding: 0;
    margin: 0px 0px 20px 0px;
    color: #5C5C5C;
    font-size:x-large;
}
.form-style-7 ul{
    list-style:none;
    padding:0;
    margin:0;  
}
.form-style-7 li{
    display: block;
    padding: 9px;
    border:1px solid #DDDDDD;
    margin-bottom: 30px;
    border-radius: 3px;
}
.form-style-7 li:last-child{
    border:none;
    margin-bottom: 0px;
    text-align: center;
}
.form-style-7 li > label{
    display: block;
    float: left;
    margin-top: -19px;
    background: #FFFFFF;
    height: 14px;
    padding: 2px 5px 2px 5px;
    color: #B9B9B9;
    font-size: 14px;
    overflow: visible;
    font-family: Corbel;
}
.form-style-7 input[type="text"],
.form-style-7 input[type="date"],
.form-style-7 input[type="datetime"],
.form-style-7 input[type="email"],
.form-style-7 input[type="number"],
.form-style-7 input[type="search"],
.form-style-7 input[type="time"],
.form-style-7 input[type="url"],
.form-style-7 input[type="password"],
.form-style-7 textarea,
.form-style-7 select
{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    width: 100%;
    display: block;
    outline: none;
    border: thin solid silver;
    border-radius:2px;
    height: 25px;
    line-height: 25px;
    font-size: 16px;
    padding: 0;
    font-family: Corbel;
}
.form-style-7 input[type="text"]:focus,
.form-style-7 input[type="date"]:focus,
.form-style-7 input[type="datetime"]:focus,
.form-style-7 input[type="email"]:focus,
.form-style-7 input[type="number"]:focus,
.form-style-7 input[type="search"]:focus,
.form-style-7 input[type="time"]:focus,
.form-style-7 input[type="url"]:focus,
.form-style-7 input[type="password"]:focus,
.form-style-7 textarea:focus,
.form-style-7 select:focus
{
}
.form-style-7 li > span{
    background: #F3F3F3;
    display: block;
    padding: 3px;
    margin: 0 -9px -9px -9px;
    text-align: center;
    color: #C0C0C0;
    font-family: Corbel;
    font-size: 11px;
}
.form-style-7 textarea{
    resize:none;
}
.form-style-7 input[type="submit"],
.form-style-7 input[type="button"]{
    background: #2471FF;
    border: none;
    padding: 10px 20px 10px 20px;
    border-bottom: 3px solid #5994FF;
    border-radius: 3px;
    color: #D2E2FF;
}
.form-style-7 input[type="submit"]:hover,
.form-style-7 input[type="button"]:hover{
    background: #6B9FFF;
    color:#fff;
}
</style>

<script type="text/javascript">
//auto expand textarea
function adjust_textarea(h) {
    h.style.height = "20px";
    h.style.height = (h.scrollHeight)+"px";
}
</script>
<!-- /styles and scripts-->
<!-- £££££££££££££££££ Area 51 £££££££££££££££££-->
<div class="form-style-7">
<%= form_for @event, :html => { :multipart => true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<ul>
<li>
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</li>
<li>
  <%= f.label :industry %><br>
  <%= f.text_field :category %>
</li>
<li>
  <%= f.label :event_Name %><br>
    <%= f.text_field :name %>
</li>
<li>
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
</li>
<li>
  <%= f.label :date %><br>
  <%= f.date_select :date %>
</li>
<li>
  <%= f.label :venue %><br>
  <%= f.text_field :venue %>
</li>
<li>
  <%= f.label :location %><br>
  <%= f.text_field :location %>
</li>
<li>
  <%= f.label :country %><br>
  <%= f.text_field :country %>
</li>
<li>
  <%= f.label :link %><br>
  <%= f.text_field :link %>
</li>

<div class="submit">
  <%= f.submit "Okay"  %> 
  <%= link_to 'Cancel', events_path %>
</div>
</ul>
<% end %>

</div>

app/views/events/edit.html.erb
<h3>Edit Event</h3>
<%#= image_tag @event.image.url(:medium) %>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<style type="text/css">
  #container{
    margin-bottom: 1em;
    /*box-shadow: -1px 1px 1px black;*/
  }
  #items{
    padding-left:2em;
    margin-top:1em;
  }
  #image-holder{
    background:none repeat scroll 0% 0% ;
    visibility: visible;
    padding-top:1em;
    padding-bottom:0.5em;
    width:300px;
    float:left;
    min-height: 300px !important;
    margin-left: 20px;
    opacity: 1;
    margin-right:3em;
    transform:none;
  }
  
  #actions{
    color:blue;
    padding-bottom:1em;
  }
  .actions{
    color:chocolate ;
  }
  .content-p{
    padding-top:0.8em;
  }
  .img{
    border:thin solid transparent;
    border-radius:2px;
    color:#ccc;
    background: none repeat scroll 0% 0% ;
    width:100%;
    visibility: visible;
  }

</style>
</div>

<!-- Navbar -->
<div class="navi navbar-fixed-top" ></div>
<div class=" navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:rgba(0,0,0,0.7)">
  <div class="nav-size container nav-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%=link_to (image_tag("thha.png", alt: "Logo white", class: "logo")), homes_path, class: "logo navbar-brand in-app", anchor: "landing" %>
    </div>
    <div class="collapse navbar-collapse text-center" >
           <ul class="ul-nav nav navbar-nav" >
            <li class="nav-background"><%= link_to "About",homes_path, :anchor => "about" %></li>
            <li class="nav-background"><%= link_to "Events", events_path %></li>
            <li class="nav-background"><%= link_to "Newsletter",homes_path, :anchor => "publications" %></li>
            <li class="nav-background"><%= link_to "Contact",homes_path, :anchor => "contact" %></li>
          </ul>  
    </div>
  </div>
<!--/.nav-collapse -->
</div>
<!-- /Navbar -->

<div id="container" class="container rows show-container"><!-- overal container-->
  <div id="items"><!--items-->
    <p id="notice"><%= notice %></p>

    <div id="image-holder">
      <div class="img">
        <%= link_to (image_tag @event.image.url(:medium)), @event.link %> 
      </div>
    </div>
  <div id="content-holder">
    <!--<p>
      <strong>Industry-I</strong>
      <%= @event.name %>
    </p>-->


    <p class="content-p">
      <strong>Event Name:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @event.category %>
    </p>
    <p>
      <strong>Theme:</strong>
      <%= @event.theme %>
    </p>
    <p>
      <strong>Venue:</strong>
      <%= @event.venue %>
    </p>
    <!--<p>
      <strong>Company:</strong>
      <%= @event.company %>
    </p>-->
    <p>
      <strong>Country:</strong>
      <%= @event.country %>
    </p>

    <!--<p>
      <strong>Organizer:</strong>
      <%#= @event.organizer %>
    </p>-->

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @event.location %>
    </p>

    <p>
      <strong>Link:</strong>
      <%= @event.link %>
    </p>

    <div id="actions">
      <% if user_signed_in? %>
      <%= link_to 'Edit', edit_event_path(@event), class: "actions" %> |
      <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Delete this Event ?' }, class: "actions" %> |
      <% end %>
      <%= link_to 'Back', events_path, class: "actions" %> 
    </div>
  </div>
  </div>
  <div class="col-sm-4">
  </div>
</div>

<!-- footer-->
<div id="footer" class="getstarted s-blue footer-nav">
  <div class="container">
    <footer>
      <div class="footer-contact">
        <p class="footer-m">&copy;  2015. Mkutano Business Travel. Part of The Stawi Group  </p>
        <!--<nav>
          <ul class="footer-2">
            <li><%= link_to "About", :anchor => "about" %> </li>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Publications",:anchor => "publications" %></li>
            <li><%= link_to "Contact ", :anchor => "contact" %></li>
          </ul>
        </nav>
        <p class="" style="margin: 0 auto; padding-top: 0.5em; word-spacing: 0.5em; color:#fff;">      Position | Connect | Grow
        </p>-->
      </div>
    </footer>
  </div>
</div>